Toast
HelixDesignSystem/helix-react pull request #116
Opened 2020-10-16 20:51 UTC by nicko-winner

Add Toast component

2020-10-20 19:06 UTC, nicko-winner commented on src/Alert/index.js
> +    <div>
notices `<>` elements don't fix the disappearing react element error.

2020-10-21 18:11 UTC, 100stacks requested changes

2020-10-21 18:11 UTC, 100stacks commented on src/Alert/index.js
> +    <div>
@nicko-winner, sorry what's this error again?  Does the `<>` cause the error on render?

2020-10-21 18:25 UTC, nicko-winner commented on src/Alert/index.js
> +    <div>
The error happens after helix removes the element from the DOM (by clicking dismiss), and you change pages in storybook. This is the error:
![2020-10-16_16-48-23](https://user-images.githubusercontent.com/35456401/96765991-68e1e400-13a8-11eb-9b67-d72ac229b60c.png)

2020-10-21 19:43 UTC, 100stacks approved these changes
Dev LGTM

2020-10-21 19:43 UTC, 100stacks commented on src/Alert/index.js
> +    <div>
Ok thanks for the explanation.  This helps alot. 👍

2020-10-21 19:43 UTC, merged