Add JSX docs view to all components
HelixDesignSystem/helix-react pull request #122
Opened 2020-11-13 19:14 UTC by nicko-winner

![2020-11-13_14-13-47](https://user-images.githubusercontent.com/35456401/99111621-7874d700-25ba-11eb-9996-9c46acf94f9b.png)

2020-11-30 21:15 UTC, 100stacks requested changes
@nicko-winner, just a few small comments/questions.  👍

2020-12-01 20:18 UTC, nicko-winner commented on README.md
> -
sure

2020-12-01 20:22 UTC, nicko-winner commented on src/Alert/stories.js
> +  jsx: { skip: 0 },
This creates a global param, and sets the arguments for storybook. We are telling the JSX plugin that is being applied globally to all stories to skip: 0 times, which means, do not exclude any markup from the JSX window display:

If you had markup that looks like this:
skip: 0 would would show all the markup.
```
<div>
     <span>
        <a></a>
     </span>
</div>
```

skip: 1. would skip the outermost div:
```
<span>
     <a></a>
</span>
```
skip: 2 would skip the outer 2 tags:
```
  <a></a>
```

2020-12-01 20:33 UTC, nicko-winner commented on src/Button/stories.js
> +  jsx: { skip: 2 },
see earlier response.

2020-12-01 22:24 UTC, 100stacks commented on src/Alert/stories.js
> +  jsx: { skip: 0 },
Ok thanks for the explanation above. 🙄

2020-12-01 22:28 UTC, 100stacks approved these changes
Dev LGTM

2020-12-01 22:28 UTC, merged