Helix-UI to 2.0
HelixDesignSystem/helix-react pull request #127
Opened 2021-01-26 20:02 UTC by nicko-winner

- Switch Modals and Popovers to use secondary button styles
- Add support to pass your own custom radio input as prop, useful for redux-redux form wrapper components.

2021-01-26 21:18 UTC, abrande approved these changes

2021-01-28 23:38 UTC, 100stacks requested changes

2021-01-28 23:38 UTC, 100stacks commented on src/ChoiceTile/stories.js
>        <ChoiceTile
### `subdued` is causing the Choice (Option) Tile to increase in size:

https://user-images.githubusercontent.com/10120600/106211885-12e2c080-618f-11eb-84d1-7cdf263b2649.mov

2021-01-29 02:09 UTC, nicko-winner commented on src/ChoiceTile/stories.js
>        <ChoiceTile
I wonder if the best way to fix this is inside of helix-ui CSS? (looks like if the line-height is removed it fixes the issue)
![2021-01-28_21-07-11](https://user-images.githubusercontent.com/35456401/106222179-05d4ca00-61ad-11eb-9222-265ea5d8386d.png)

2021-01-29 17:26 UTC, abrande approved these changes

2021-02-01 16:36 UTC, nicko-winner commented on src/ChoiceTile/stories.js
>        <ChoiceTile
From the official docs in tablet / mobile sized browser: 
![2021-02-01_11-34-05 (1)](https://user-images.githubusercontent.com/35456401/106488315-964b2d00-6481-11eb-96ca-37a0fbba4282.gif)
https://helixdesignsystem.github.io/helix-ui/components/choice-tile/

2021-02-01 19:41 UTC, 100stacks approved these changes
Great work, Nicko!!! 👏🎉 

Dev LGTM

2021-02-01 19:43 UTC, merged